### ISSUE TITLE
Errors from static code analysis: .editorconfig

### ISSUE THREAD

**Issue by abugey** [systopia/de.systopia.mailbatch#12]
By analysis via PHPStorm inspect code feature the following error was found:
`.editorconfig: line 224: 'global' is not allowed here`

**Comment by jensschuppe** [comment]
Since `.editorconfig` files are irrelevant for functionality, and this relates to a proprietary IDE-specific config parameter, I'd suggest ignoring this. Also, those `.editorconfig` files violate CiviCRM's Coding standards - just saying ...

**Comment by bjendres** [comment]
What we've done in all the other extensions is to set it to ``auto`` instead of ``global``, and that should be fine.

**Comment by jensschuppe** [comment]
Should be fixed with e9f099618119664bd5e4a6a7bc02a64aa451b4b8 then ...
