### ISSUE TITLE
Attachment Provider Interface

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.mailbatch#3]
In terms of the attachments to be sent, it would be nice if we had a Symfony event that allows other extensions/systems to locate or generate arbitrary attachment files to be sent out. The existing methods ("token based local file name" and "contribution invoice") could easily be re-implemented for this, too.

**Comment by jensschuppe** [comment]
This is being implemented in the [`feature/attachments`](https://github.com/systopia/de.systopia.mailbatch/compare/feature/attachments) branch.
