### ISSUE TITLE
Consider refactoring attachment interface into its own extension

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.mailbatch#6]
Follow-up to #3

The attachment interface should be considered being refactored into its own extension for not relying on MailBatch when using it with other extensions, e.g. [de.systopia.eventmessages](https://github.com/systopia/de.systopia.eventmessages).

**Comment by bjendres** [comment]
I don't think this should be considered "closed" yet, because right now (if I'm not mistaken) somebody upgrading from the last version would simply lose any attachment functionality without any explication why or instructions on how to enable them again....

IMHO This should at least be mentioned in the readme file, and the migration script should create a popup with a link.

**Comment by jensschuppe** [comment]
1. Documentation on this is already in the making and will describe the new behavior
2. It is a new major version that is implementing attachments differently, so users should be aware of breaking changes; also, there's no loss of data/configuration/etc.
3. Those changes will be described in the release notes as well
4. The Mail Attachments extension already has documentation
5. There are help texts in Mail Batch forms informing the user about Mail Attachments missing

So, there's plenty of explications and instructions and I don't see the need for any more popups, warnings, or whatever. But let's keep this open at least until the docs are ready.

**Comment by bjendres** [comment]
> So, there's plenty of explications and instructions and I don't see the need for any more popups, warnings, or whatever. But let's keep this open at least until the docs are ready.

Well, the user experience if you update the extension via the UI is that the attachment functionality, along with your current attachment configuration, is gone without any warning. 

Don't worry, I'll add a simple warning message to the upgrader.

**Comment by jensschuppe** [comment]
So this is waiting for documentation now.

**Comment by jensschuppe** [comment]
Documentation is underway separately, let's close this.
