### ISSUE TITLE
Merge mail attachment service/interface into core

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.mailbatch#9]
At the 2022 Manchester sprint @totten, @colemanw, and @bjendres briefly talked about the prospect of using the attachment service defined by this extension in the CiviCRM core. 

It would require a reasonably big core PR from us (SYSTOPIA+?) to apply this to all core forms where attachments can be selected.

On the upside, it would also allow us to use all our attachment providers in the various extensions to work with core mailing actions - and, of course, other people to provide their own custom attachment provider services as well.

**Comment by jensschuppe** [comment]
@bjendres Doesn't this refer to [systopia/de.systopia.mailattachment](https://github.com/systopia/de.systopia.mailattachment) instead? And wouldn't this be an issue for CiviCRM Core?

Also, this might, as a first step, be done using hooks within the *Mail Attachments* extension for some Core forms. Also, other extensions can already provide attachment providers using the *Mail Attachments* extension's framework, so adding this to Core isn't a blocker for this.

You are right, however, that Core forms/functionality should not rely on or implement 3rd party extensions' code.

**Comment by bjendres** [comment]
> @bjendres Doesn't this refer to [systopia/de.systopia.mailattachment](https://github.com/systopia/de.systopia.mailattachment) instead?

Yes. But it doesn't hurt to have it here, too.
